package jm.task.core.jdbc.dao;

import jm.task.core.jdbc.model.User;
import jm.task.core.jdbc.util.Util;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;

import static jm.task.core.jdbc.util.Util.getConnection;

@Component
public class UserDaoJDBCImpl implements UserDao {
    private Connection connection = getConnection();



    public void createUsersTable() { // TODO

        Statement statement = null;
        try {
            statement = connection.createStatement();
            String createTableSQL = "CREATE TABLE IF NOT EXISTS Users ("
                    + "id bigint primary key generated by default as identity,"
                    + "name varchar(100) not null,"
                    + "last_name varchar(100) not null,"
                    + "age smallint not null)";

            statement.execute(createTableSQL);
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    public void dropUsersTable() {
        Statement statement = null;
        try {
            statement = connection.createStatement();
            String dropTableSQL = "DROP TABLE IF EXISTS Users";
            statement.execute(dropTableSQL);
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    public void saveUser(String name, String lastName, byte age) { //TODO
        try {
            PreparedStatement preparedStatement =
                    connection.prepareStatement("INSERT INTO Users VALUES(1, ?, ?, ?)");

            preparedStatement.setString(1, name);
            preparedStatement.setString(2, lastName);
            preparedStatement.setByte(3, age);

            preparedStatement.executeUpdate();
        } catch (SQLException throwables) {
            throwables.printStackTrace();
        }
    }

    public void removeUserById(long id) {
        PreparedStatement preparedStatement =
                null;
        try {
            preparedStatement = connection.prepareStatement("DELETE FROM Users WHERE id=?");

            preparedStatement.setLong(1, id);

            preparedStatement.executeUpdate();
        } catch (SQLException throwables) {
            throwables.printStackTrace();
        }
    }

    public List<User> getAllUsers() {
        List<User> allUsers = new ArrayList<>();

        try {
            Statement statement = connection.createStatement();
            String SQL = "SELECT * FROM Users";
            ResultSet resultSet = statement.executeQuery(SQL);

            while (resultSet.next()) {
                User user = new User();

                user.setId(resultSet.getLong("id"));
                user.setName(resultSet.getString("name"));
                user.setLastName(resultSet.getString("email"));
                user.setAge(resultSet.getByte("age"));

                allUsers.add(user);
            }

        } catch (SQLException throwables) {
            throwables.printStackTrace();
        }
        return allUsers;
    }

    public void cleanUsersTable() {
        Statement statement = null;
        try {
            statement = connection.createStatement();
            String dropTableSQL = "TRUNCATE TABLE Users";
            statement.execute(dropTableSQL);
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }
}
